version: '3'
services:
  app:
    image: rex/login:dev
    ports:
      - 8080:8080
      # - 9990:9990
    environment:
      TZ: Asia/Shanghai
      #DB_VENDOR: postgres
      #DB_ADDR: host.docker.internal:5432
      DB_VENDOR: mysql
      DB_ADDR: rm-8vb596im619h36870so.mysql.zhangbei.rds.aliyuncs.com
      DB_PORT: 3306
      DB_USER: tkdbman
      DB_DATABASE: tkdb
      DB_PASSWORD: Tkdbman@Pass
      #JDBC_PARAMS: 'useSSL=false&verifyServerCertificate=false'

      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin@123

      #KEYCLOAK_WELCOME_THEME=XXX
      #KEYCLOAK_DEFAULT_THEME=XXX
      #PROXY_ADDRESS_FORWARDING: true
      #KEYCLOAK_HOSTNAME: local.login.alizhongzhi.top
    #volumes:
      #- ./themes/aa:/opt/jboss/keycloak/themes/aa
    extra_hosts:
      - "smtp.service.uri:113.96.208.92"
