version: '3'
services:
  app:
    image: registry-vpc.cn-hangzhou.aliyuncs.com/teamkits/login:20221223171438
    ports:
      - 8080:8080
      - 8433:8433
    environment:
      KC_DB: mysql
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: ****
      KC_DB_URL_DATABASE: kcdb-test
      KC_DB_URL_HOST: rm-bp15743n8nmzjnt0d.mysql.rds.aliyuncs.com
      KC_DB_URL_PROPERTIES: "?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8"
      KEYCLOAK_ADMIN: ****
      KC_DB_PASSWORD: ********
      KEYCLOAK_ADMIN_PASSWORD: ********
    extra_hosts:
      - "smtp.service.uri:113.96.208.92"
    volumes:
      - .certs/auth.teamkits.online.pem:/opt/keycloak/certs/tls.crt:ro
      - .certs/auth.teamkits.online.key:/opt/keycloak/certs/tls.key:ro
    command:
      - start
      - --optimized
      - --proxy=edge
      - --http-enabled=true
      - --hostname-strict=false
      - --https-certificate-file=/opt/keycloak/certs/tls.crt
      - --https-certificate-key-file=/opt/keycloak/certs/tls.key
