apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: login
spec:
  template:
    metadata:
      name: 'login-service'
      annotations:
        # Service可启动的最小POD数，未设置/或设置为0时，即scale-to-zero特性，该配置用于控制「冷启动时间」
        autoscaling.knative.dev/minScale: "0"
        # Service可启动的最大POD数，未设置时KPA将根据请求数创建POD且数量无限制，该配置用于控制「成本」
        # autoscaling.knative.dev/maxScale: "100"

        # 指每个POD能接受的最大请求数是「10」，KPA会根据该值调整POD的数量——即动态扩(缩)容
        # autoscaling.knative.dev/target: "10"

        # autoscaling.knative.dev/window: "60s"
        # autoscaling.knative.dev/targetBurstCapacity: "100"
    spec:
      containers:
        - image: login-image.name
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              valueFrom:
                secretKeyRef:
                  key: TZ
                  name: login-service-secret
            - name: DB_ADDR
              valueFrom:
                secretKeyRef:
                  key: DB_ADDR
                  name: login-service-secret
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: DB_DATABASE
                  name: login-service-secret
            - name: DB_VENDOR
              valueFrom:
                secretKeyRef:
                  key: DB_VENDOR
                  name: login-service-secret
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  key: DB_PORT
                  name: login-service-secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USER
                  name: login-service-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: login-service-secret
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_USER
                  name: login-service-secret
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KEYCLOAK_PASSWORD
                  name: login-service-secret
