apiVersion: v1
kind: Service
metadata:
  name: login-svc
  labels:
    app: login-svc
spec:
  clusterIP: None
  selector:
    app: login-pod
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
